CREATE TABLE budget (
    _id integer primary key autoincrement,
    title text,
    category_id long not null,
    currency_id long not null,
    amount integer not null,
    include_subcategories integer not null default 1,
    start_date long,
    end_date long,
    repeat integer,
    recur text,
    recur_num integer not null default 0,
    is_current integer not null default 1,
    parent_budget_id long not null default 0,
    project_id text,
    expanded integer not null default 0,
    include_credit integer not null default 1,
    updated_on TIMESTAMP DEFAULT 0,
    remote_key text,
    budget_account_id long,
    budget_currency_id long);
